// Generated by CoffeeScript 1.6.3
(function() {
  var HttpClient, api, http, inspect;

  inspect = require('eyes').inspector({
    maxLength: false
  });

  HttpClient = require('scoped-http-client');

  http = function(url) {
    return HttpClient.create(url).header('User-Agent', "Hubot/" + this.version);
  };

  api = require('./scripts/hudson-test-manager/api.coffee');

  api.getBuildStatus(http, function(err, res, body) {
    inspect(err, 'Error');
    return inspect(JSON.parse(body), 'Body');
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
