// Generated by CoffeeScript 1.6.3
(function() {
  var inspect;

  inspect = require('eyes').inspector({
    maxLength: false
  });

  module.exports = {
    authRequest: function(http, url) {
      var req;
      req = http(url);
      return req.auth('mdarveau', 'password');
    },
    getBuildStatus: function(http, callback) {
      var req;
      req = this.authRequest(http, "https://solic1.dev.8d.com:8443/view/ftk-tests/api/json");
      return req.get()(callback);
    }
  };

}).call(this);

/*
//@ sourceMappingURL=api.map
*/
